export const WHITE_PAPER_URL = "https://docs.google.com/document/d/1bqNa7AG0HZSRerClKIZPwohYVb3YgxJPAUXzgjz__lE/edit?usp=sharing"
export const GITHUB_URL = "https://github.com/SOLAXDEX"
export const DISCORD_URL = "https://discord.gg/QFqHktzX3c%20"
export const TWITTER_URL = "https://twitter.com/SOLAXAPP"
export const MEDIUM_URL = "https://medium.com/@Sola-x"